### ISSUE TITLE
Migrate cinful/notebooks to docs/notebooks

### ISSUE THREAD

**Issue by tijeco** [wilkelab/cinful#38]
Maybe it doesn't have to be docs/notebooks, selfishly, I just don't want to change a lot of relative paths...

Regardless, this could potentially be a big, but helpful undertaking. I mostly want it to be a way to do a demonstration of what's going on under the hood with the various rules, files, and functions. When this becomes a bonafide package, all the functions will be declared in cinful.py or maybe util.py so they can be imported somehow in the snakefiles, but more importantly, they can also be called in the notebooks!

I have no such desires to make this available by 1.0.0

**Comment by AaronFeller** [comment]
Completed
