### ISSUE TITLE
add support for neubi

### ISSUE THREAD

**Issue by tijeco** [wilkelab/cinful#48]
This will require a bit of fenagling to get working properly. It may even be an issue of just getting the model files and writing a way to load them. Since neubi the library itself is not installable from conda, and the library can have weird issues. I don't know exactly what this will require, but it is certainly not something I think absolutely needs to be present for v1.0.0

**Comment by AaronFeller** [comment]
Not required for current scope of project. Potential to reopen in the future, though neubi may be used separately.
